API_KEY="YOUR-API-KEY"
API_SECRET="YOUR-API-SECRET"
ACCESS_TOKEN="YOUR-ACCESS-TOKEN"
ACCESS_TOKEN_SECRET="YOUR-ACCESS-TOKEN-SECRET"

#THIS FILE IS AN EXAMPLE
#FILL IT WITH YOUR TWITTER CREDENTIALS AND RENAME IT TO secret.py
